### ISSUE TITLE
The Downloadable Model File on the model creator website does not show as a model creator file so I cannot load it ;(

### ISSUE THREAD

**Issue by EB57PzUhYmQsMm** [Ocelot5836/ModelCreatorApp#1]
Love the mod~

**Comment by Ocelot5836** [comment]
I submitted a pr to hopefully fix that all up and any older model creator files will no longer be compatible.

**Comment by Ocelot5836** [comment]
Fixed in https://github.com/MrCrayfish/GitWeb-Sites/pull/24
